// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xwfkrjtqcqmmpclioakd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh3ZmtyanRxY3FtbXBjbGlvYWtkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxMzM2OTcsImV4cCI6MjA2MDcwOTY5N30.Efvr6Zkt4jXREOqAopvhTihguuMLEr0nP0cEs-WlMu0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);